# Generated by Django 3.0.3 on 2020-06-20 08:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procuct_id', models.CharField(max_length=50, unique=True)),
                ('product_name', models.CharField(max_length=50, unique=True)),
                ('product_category', models.CharField(max_length=50, unique=True)),
                ('product_owner', models.CharField(max_length=50, null=True)),
                ('product_short_desc', models.CharField(max_length=100, null=True)),
                ('product_desc', models.CharField(max_length=5000, null=True)),
                ('prodcut_image_pat', models.CharField(max_length=200, null=True)),
                ('created_dt', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('updated_dt', models.DateTimeField(default=datetime.datetime.now, null=True)),
            ],
        ),
    ]
