# Generated by Django 3.0.3 on 2020-06-28 08:42

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='product_id',
        ),
        migrations.AddField(
            model_name='subscription',
            name='created_dt',
            field=models.DateTimeField(
                default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='prodcut_image_pat',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='product_price',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='quantity',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='subscription_price',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='updated_dt',
            field=models.DateTimeField(
                default=datetime.datetime.now, null=True),
        ),
    ]
