# Generated by Django 3.0.3 on 2020-06-28 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_auto_20200628_0842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='created_dt',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='prodcut_image_pat',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='product_price',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='subscription_price',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='updated_dt',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='user_id',
        ),
    ]
