# Generated by Django 3.0.3 on 2020-06-28 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_auto_20200628_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='subscription_id',
        ),
    ]
