# Generated by Django 3.0.3 on 2020-06-25 08:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=50, unique=True)),
                ('course_name', models.CharField(max_length=50, unique=True)),
                ('course_category', models.CharField(max_length=50, unique=True)),
                ('course_owner', models.CharField(max_length=50, null=True)),
                ('course_short_desc', models.CharField(max_length=100, null=True)),
                ('course_desc', models.CharField(max_length=5000, null=True)),
                ('course_image_path', models.CharField(max_length=200, null=True)),
                ('created_dt', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('updated_dt', models.DateTimeField(default=datetime.datetime.now, null=True)),
            ],
        ),
    ]
