# Generated by Django 3.0.3 on 2020-06-26 06:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_id', models.CharField(max_length=50, unique=True)),
                ('lesson_name', models.CharField(max_length=50, unique=True)),
                ('lesson_owner', models.CharField(max_length=50, null=True)),
                ('lesson_short_desc', models.CharField(max_length=100, null=True)),
                ('lesson_desc', models.CharField(max_length=5000, null=True)),
                ('lesson_image_path', models.CharField(max_length=200, null=True)),
                ('lesson_video_path', models.CharField(max_length=200, null=True)),
                ('created_dt', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('updated_dt', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('course_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='edu.Course', to_field='course_id')),
            ],
        ),
    ]
