# Generated by Django 3.0.3 on 2020-06-28 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_address',
            new_name='user_address_landmark',
        ),
        migrations.AddField(
            model_name='profile',
            name='user_district',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_pincode',
            field=models.IntegerField(null=True),
        ),
    ]
